CLAUSES:THERE ARE TWO TYPES
CREATE DATABASE CLAUSES;

USE CLAUSES;

CREATE TABLE EMPLOYEE(ENO INT,ENAME VARCHAR(30),EJOB VARCHAR(30),ESALARY MONEY,EDEPTNO INT);

INSERT EMPLOYEE VALUES(1217,'AGASYA','BIGDATA',25000,90),(002,'MANDAVYA','MAINFRAMES',24000,68),(5627,'VISHNU','DEVELOPER',95000,89),(8956,'ASHOK','SQL',15000,56),
(5656,'LINDA','DEVELOPER',76888,432),(4567,'BOB','BIGDATA',67999,87),(5555,'MANOJ','MAINFRAMES',25000,77),(2345,'HARI','DEVELOPER',56000,55),
(9090,'JACK','SQL',65000,65),(1010,'ROSE','TESTER',45000,45);

SELECT * FROM EMPLOYEE;
1)GROUP BY CLAUSE:IT IS USED TI GROUPING THE SIMILAR DATA BASED ON THE COLUMNS.

GROUP BY CLAUSE USING AGGERATION FUNCTIONS WITH SINGLE COLUMN NAME:
SELECT EJOB,COUNT(*) FROM EMPLOYEE GROUP BY EJOB;

SELECT EJOB,SUM(ESALARY) FROM EMPLOYEE GROUP BY EJOB;

SELECT EJOB,MAX(ESALARY) FROM EMPLOYEE GROUP BY EJOB;

SELECT EJOB,MIN(ESALARY) FROM EMPLOYEE GROUP BY EJOB;

SELECT EJOB,AVG(ESALARY) FROM EMPLOYEE GROUP BY EJOB;

GROUP BY CLAUSE USING AGGERATION FUNCTIONS WITH MULTIPLE COLUMN NAME:
SELECT EJOB,COUNT(*),EDEPTNO FROM EMPLOYEE GROUP BY EJOB,EDEPTNO;

2)HAVING CLAUSE:IT IS USED TO FILTER THE RECORDS AFTER GROUPING THE DATA BASED ON CONDITION.
SELECT EJOB,COUNT(*) FROM EMPLOYEE GROUP BY EJOB HAVING COUNT(*) < 3;

SELECT EJOB,SUM(ESALARY) FROM EMPLOYEE GROUP BY EJOB HAVING SUM(ESALARY)>100000;