USE CLASS;

CREATE TABLE EMP(EMPID INT IDENTITY(100,5),EMPNAME VARCHAR(30),EMPSALARY MONEY);

SELECT * FROM EMP;

INSERT EMP VALUES('AGASYA',25000),('LOKHYA',24500),('PRIYA',23000),('MADHU',23765);

INSERT EMP(EMPID,EMPNAME,EMPSALARY) VALUES(120,'SWATHI',809);-->NOT EXECUTED TO OVERCOME THIS PROBLEM USE SET IDENTITY_INSERT EMP ON

SET IDENTITY_INSERT EMP ON; 

