CREATE DATABASE EXJIONS;

USE EXJIONS;

CREATE TABLE STUDENT(STUID INT,STUNAME VARCHAR(30),STUEMAIL VARCHAR(40),STUCOURSEID INT) 

INSERT STUDENT VALUES(101,'AGASYA','agasya@gmail.com',10),(102,'MANDAVYA','mandavya@gmail.com',20),(103,'VISHNU','vishnu@gmail.com',30),
(104,'ASHOK','ashok@gmail.com',40);

SP_RENAME 'STUDENT.STUCOURSEID','COURSE_ID';

SELECT * FROM STUDENT;
SELECT * FROM COURSE;

CREATE TABLE COURSE(COURSE_ID INT,COURSE_NAME VARCHAR(30),COURSE_FEES DECIMAL(6,2));

INSERT COURSE VALUES(10,'CORE JAVA',8500),(20,'MAINFRAMES',9000),(40,'TESTING',6543),(50,'SQL SERVER',5500);

INNSER JOINS:RETRIVE THE DATA FROM MULTIPLE TABLES BASED ON EQUALITY CONDITION AND
MUST AND SHOULD HAVE COMMAN COLOUM IN BOTH TABLES(COURSE_ID) AND COMMOM COLOUM DATATYPE MUST BE SAME.

SELECT * FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSE_ID = COURSE.COURSE_ID;(WE WILL GET ONLY MATCHING DATA)