USE  EXJIONS;

SELECT * FROM STUDENT;

SELECT * FROM COURSE;

OUTERJOIN:IT WILL RETRIVR BOTH MATCHING AMD UN-MATCHING DATA.THESE ARE THREE TYPES
1)LEFT OUTER JOIN:IT RETRIVRS MATCHING DATA FROM ALL THE TABLES BUT UN-MATCHING DATA ON LEFT HAND SIDE(LHS) OF TABLE ONLY

SELECT * FROM STUDENT S LEFT OUTER JOIN COURSE C ON S.COURSE_ID = C.COURSE_ID;

--2)RIGHT OUTER JOIN:IT RETRIVES MATCHING DATA FROM ALL THE TABLES BUT UN-MATCHING DATA ON RIGHT HAND SIDE(RHS) TABLE ONLY

SELECT * FROM STUDENT S RIGHT OUTER JOIN COURSE C ON S.COURSE_ID = C.COURSE_ID;

--3)FULL OUTER JOIN:IT RETRIVES BOTH MATCHING AND UN-MATCHING DATA FROM ALL THE TABLES

SELECT * FROM STUDENT S FULL OUTER JOIN COURSE C ON S.COURSE_ID = C.COURSE_ID;

CROSS JOINS: THESE ARE USED TO PRODUCT OF TABLES(M X N)
--HERE NO CONDITIONS ARE APPLIED

SELECT * FROM STUDENT CROSS JOIN COURSE;

NATURAL JOINS: THESE ARE USED TO AVOID DUPLICATE COLUMNS AND THE NATURAL JOINS ARE NOT SUPPOPRTED BY SQL SERVER.