USE CLASS1;--DATABASE
PRIMARY KEY AND FOREIGN KEY:THESE ARE USED TO MAKE RELATIONSHIP BETWEEN TEO OR MORE THAN TWO TABLES
CONDITIONS:
1)ONE TABLE SHOULD CONTAIN PRIMARY KEY AND OTHER SHOULD CONTAIN FOREIGN KEY
2)NEED A COMMON COLUMN IN BOTH TABLES
3)THE COMMON COLUMN DATATYPE SHOULD BE SAME IN BOTH THE TABLES

STEP:1
CREATE TABLE DEPT(DEPTNO INT PRIMARY KEY,DEPTNAME VARCHAR(30),DEPTLOCATION VARCHAR(30));--PARENT TABLE

STEP:2
INSERT DEPT VALUES(101,'JAVA','HYD'),(102,'C','BANGLORE'),(103,'C++','CHENNAI'),(104,'PYTHON','PUNE');

STE:3
SELECT * FROM DEPT;
SELECT * FROM EMP;

STEP:4
CREATE TABLE EMP(EMPID INT,EMPNAME VARCHAR(30),EMPSALARY MONEY,
DEPTNO INT FOREIGN KEY REFERENCES DEPT(DEPTNO));--CHILD TABLE

STEP:5
INSERT EMP VALUES(1,'AGASYA',85000,101);--ALLOWED
INSERT EMP VALUES(2,'MANDAVYA',65000,102),(3,'VISHNU',59000,103),(4,'ASHOK',89765,104);--ALLOWED
INSERT EMP VALUES(5,'JACK',5000,105);--NOTALLOEWD
DELETE EMP WHERE EMPID=5;
