USE EXJIONS;

SELECT * FROM COURSE;

SELECT * FROM STUDENT;

SELECT * FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSE_ID = COURSE.COURSE_ID;

SELECT * FROM STUDENT S LEFT OUTER JOIN COURSE C ON S.COURSE_ID = C.COURSE_ID;

SELECT * FROM STUDENT S RIGHT OUTER JOIN COURSE C ON S.COURSE_ID  = C.COURSE_ID;

SELECT * FROM STUDENT S FULL OUTER JOIN COURSE C ON S.COURSE_ID = C.COURSE_ID;

SELECT * FROM STUDENT CROSS JOIN COURSE;

SELF JOIN:JOINING DATA BY ITSELF IS CALLED AS SELF JOIN.IT IS IMPLEMENTED WITH ALIAS NAME OF THE TABLE AND IT CAN BE IMPLEMENTED ON SINGLE TABLE ONLY.
IT IS USED WHEN WE COMPARE A COLUMN VALUES WITH IN A SAME TABLE THEN WE USE SELF JOINING

EQUI JION:
SELECT * FROM STUDENT,COURSE WHERE STUDENT.COURSE_ID = COURSE.COURSE_ID;

NON-EQUI JOIN:
