SHOW DATABASES;

CREATE DATABASE TCL;

USE TCL;

CREATE TABLE BRANCH(BRANCHID INT,BRANCHNAME VARCHAR(50),BRANCHLOCATION VARCHAR(50));

INSERT BRANCH VALUES(1217,'SBI','HYDERABAD');
UPDATE BRANCH SET BRANCHLOCATION = 'PIDUGURALLA' WHERE BRANCHID = 1217;
DELETE FROM  BRANCH WHERE BRANCHID = 1217;
SELECT * FROM BRANCH;
IN TCL THE DML OPERATIOLAN COMMANDS ARE PERMENT,SO WE CAN NOT APPLY TCL(ROLLBACK) ON DML QUARYES
BEGIN TRANSACTION
ROLLBACK